### PR TITLE
Updating to webpack 4.8.x

### PR DESCRIPTION
**Pull request by jarnell**

### CODE REVIEW

**Review by awartoft — APPROVED** [review]
Looks good to me, but I'm not a web pack expert. My main question is if the vendor bundle retains the same hash if the vendor modules are unchanged. So when deploying a new application without updating dependencies the vendor.js retains the same file name thus the clients won't need to download it again?

**Comment by jarnell** [comment]
@macnibblet Yes, we are using `chunkhash` to cache bust build files = files get the same filename as long as they're not changed. E.g. if I edit Button.js in the starter kit, only common.js (where Button.js code ends up) and manifest.js (telling the browser that common.js has been updated) would get new hashes. All other bundles, including vendor, would stay the same.

**Review by simborg — APPROVED** [review]
I'd like to see an addition to .flowconfig with esproposal.optional_chaining = enable. 
Are the environmental variables (__DEV__, __PROD__) added as globals to eslintconfig or have the specs changed for those variables with webpack 4^?

**Comment by awartoft** [comment]
@jarnell Can we get an upgrade guide?

**Comment by jarnell** [comment]
@Valmorbus Fixed!

@macnibblet I guess the easiest way to upgrade a project using the current version is to look at the diff, especially config/webpack.<common/prod/dev>.js and update the project manually.

**Comment by jarnell** [comment]
Finally merging this so I don't get notifications of security issues with some old version of serve.

**Pull request merged**
